import type { LucideIcon } from 'lucide-react';
import {
  Map,
  ClipboardList,
  GraduationCap,
  Briefcase,
  Award,
  Calculator,
  BookOpen,
  User,
  Bot,
  FileText,
  Folder,
  AlertTriangle,
  Target,
  CheckCircle2,
  Building2,
  Link,
  Sparkles,
  Star,
  Globe,
  Scan,
  Heart,
  ShieldCheck,
  ScrollText,
  Landmark,
  DollarSign,
  Paperclip,
  Mail,
  Search,
  Pencil,
  Phone,
  MapPin,
  Leaf,
  FolderOpen,
  Route,
  Lightbulb,
  TrendingUp,
  Tag,
  Settings,
  Lock,
  Image,
  Shield,
  Circle,
  Newspaper,
} from 'lucide-react';

export const STAGE_ICONS: Record<string, LucideIcon> = {
  planning: Map,
  prepare: ClipboardList,
  studying: GraduationCap,
  graduate: GraduationCap,
  skilled: Briefcase,
  pr: Award,
};

export const ACTION_ICONS: Record<string, LucideIcon> = {
  calculator: Calculator,
  book: BookOpen,
  user: User,
  bot: Bot,
  fileText: FileText,
  folder: Folder,
  alert: AlertTriangle,
  briefcase: Briefcase,
  target: Target,
  check: CheckCircle2,
  building: Building2,
  link: Link,
  award: Award,
  globe: Globe,
  star: Star,
  map: Map,
  sparkles: Sparkles,
  trendingUp: TrendingUp,
};

export const QUICK_TOOL_ICONS: Record<string, LucideIcon> = {
  'visa-guide': BookOpen,
  calculator: Calculator,
  documents: Folder,
  jobs: Briefcase,
  compass: Bot,
  consultancies: Link,
  news: Newspaper,
};

export const DOC_TYPE_ICONS: Record<string, LucideIcon> = {
  PASSPORT: Scan,
  IELTS_TRF: FileText,
  PTE_SCORE: FileText,
  TOEFL_SCORE: FileText,
  COE: ClipboardList,
  OSHC: Heart,
  DEGREE: GraduationCap,
  TRANSCRIPT: FileText,
  EMPLOYMENT_LETTER: Briefcase,
  SKILLS_ASSESSMENT: TrendingUp,
  POLICE_CLEARANCE: ShieldCheck,
  HEALTH_EXAM: Building2,
  BIRTH_CERTIFICATE: ScrollText,
  MARRIAGE_CERTIFICATE: Heart,
  BANK_STATEMENT: Landmark,
  PAYSLIP: DollarSign,
  OTHER: Folder,
};

export {
  Map,
  ClipboardList,
  GraduationCap,
  Briefcase,
  Award,
  Calculator,
  BookOpen,
  User,
  Bot,
  FileText,
  Folder,
  AlertTriangle,
  Target,
  CheckCircle2,
  Building2,
  Link,
  Sparkles,
  Star,
  Globe,
  Scan,
  Heart,
  ShieldCheck,
  ScrollText,
  Landmark,
  DollarSign,
  Paperclip,
  Mail,
  Search,
  Pencil,
  Phone,
  MapPin,
  Leaf,
  FolderOpen,
  Route,
  Lightbulb,
  TrendingUp,
  Tag,
  Settings,
  Lock,
  Image,
  Shield,
  Circle,
};
